### ISSUE TITLE
Version 1.3.3 apparently only published for Python2

### ISSUE THREAD

**Issue by ksonj** [hfaran/Tornado-JSON#103]
Hej, just wanted to bring to your attention that version 1.3.3 on https://pypi.python/org only has artifacts for Python2. I guess that's not intended as v1.3.2 does have a build for Python3.

I'd have at least expected to find the sources there. Funny thing is, pipenv doesn't seem to realize that that version isn't available for Python3 and happily adds 1.3.3 to the Pipfile.lock, which then blows up on installation.

Many thanks for this library!

**Comment by hfaran** [comment]
Well that's odd... looks like you're right, there was only a py2 wheel published. I've pushed the source tarball as well now so that hopefully that solves this problem. Can you retry and see what happens?

**Comment by hfaran** [comment]
Okay, I just checked my bash history and it seems like I indeed only specified `bdist_wheel` last time when I ran the command. My bad. 😨

**Comment by ksonj** [comment]
:+1: all good now, thanks!
