### ISSUE TITLE
Consider additional parameters in main response object.

### ISSUE THREAD

**Issue by Deiru2k** [hfaran/Tornado-JSON#43]
Right now, if I a successful request is served, {'status': 'success', 'data': 'YOURDATA'} will be in an output. It would be nice if one could provide additional information (i.e. total number of objects and page offset for pagination) inside an additional parameter, like {'status': 'success', 'data': 'YOURDATA', "_meta": {"offset" 10, "totalCount": 24}}.
I know that this is kinda against JSSend specification, but I think that this will be a very nice feature.

**Comment by hfaran** [comment]
Going to close this because I don't think this would be in appropriate scope. A very easy way to accomplish this would be to simply add the `_meta` keyword your actual data response, i.e.,:

```json
{"status": "success", "data": {"_meta": ..., "foo": "bar", ...}}
```

This would then still fit within the confines of JSend.
