### ISSUE TITLE
Stacked decorators with @schema.validate and @gen.coroutine

### ISSUE THREAD

**Issue by malexh** [hfaran/Tornado-JSON#59]
First, thanks for developing this extension. It is extremely useful.  Now for the issue.
When I use the `@schema.validate` decorator as specified, it works perfectly.  Example:

```python
class ProfilesAPIHandler(APIHandler):
	__url_names__ = ["profiles"]

class ProfileListHandler(ProfilesAPIHandler):
    @schema.validate(...)
    def get(self):
        ...

class ProfileIdHandler(ProfilesAPIHandler):
    @schema.validate(...)
    def get (self, account_id):
        ...
```

The above works great!

Now, I want to use `@gen.coroutine` to do some async calls and speed up requests.  When I add in the decorator, I get doubled routes.  For example:

```python
class ProfileListHandler(ProfilesAPIHandler):
    @schema.validate(...)
    @gen.coroutine
    def get (self):
        ...

class ProfileIdHandler(ProfilesAPIHandler):
    @schema.validate(...)
    @gen.coroutine
    def get (self, account_id):
        ...
```

As a result of the above, the routes get mangled.  The above results in these routes:

    "/api/v1/accounts/profiles/?",
    "<class 'handlers.api.v1.accounts.ProfileListHandler'>"
 
    "/api/v1/accounts/profiles/?",
    "<class 'handlers.api.v1.accounts.ProfileIdHandler'>"
  
    "/api/v1/accounts/profiles/(?P<account_id>[a-zA-Z0-9_]+)/?$",
    "<class 'handlers.api.v1.accounts.ProfileIdHandler'>"

For some reason, the ProfileIdHandler class gets returned as a route to both /profiles/ and /profiles/{}.  This doesn't happen if @gen.coroutine is removed.  Unfortunately, if I put @gen.coroutine above the @schema.validate, the coroutine does not work at all.  Also, please note that I have a PUT method in ProfileIdHandler (though it isn't shown in the example), and it is also getting doubled into both /profiles and /profiles/{}.  I'd love help resolving this issue as it is a blocker for me right now.

**Comment by malexh** [comment]
Note I'm experiencing this behavior on python 3.4 with the url_names super.

**Comment by hfaran** [comment]
Hi @malexh,

Thanks for reporting this; can you confirm which version you are seeing this on (I'm assuming you're on 1.1.0 from PyPI but just double-checking)?

Also, what routes do you get without decorating your methods with `@gen.coroutine`? It is really odd that that is triggering this issue.

I unfortunately will most likely not have time to dig into this issue until some time next week as I am busy with school and other commitments, currently. However, if you could provide the above information, and expand on this further in anyway, that probably help a lot in debugging this.

Thanks!

**Comment by hfaran** [comment]
Also, I edited your comment for readability (mostly adding syntax highlighting); hope you don't mind. :)

**Comment by malexh** [comment]
Thanks for adding the syntax highlighting for me.  I am on version 1.1.0.  Without @gen.coroutine, I get these (correct) routes:

    "/api/v1/accounts/profiles/(?P<account_id>[a-zA-Z0-9_]+)/?$",
    "<class 'handlers.api.v1.accounts.ProfileIdHandler'>"
  
    "/api/v1/accounts/profiles/?",
    "<class 'handlers.api.v1.accounts.ProfileListHandler'>"

**Comment by malexh** [comment]
I believe I discovered the root cause of the problem.  It looks like any class method where there are extra arguments, if that method is decorated with @gen.coroutine then the route is not built properly.  For example from the helloworld demo:

```python
    class Greeting(APIHandler):
        @schema.validate(...)
        def get(self, fname, lname):
```
This will return the correct route:

    ".../greeting/(?P<fname>[a-zA-Z0-9_]+)/(?P<lname>[a-zA-Z0-9_]+)/?$", 
    "<class 'helloworld.Greeting'>"

If you modify that method to make it async:

```python
    class Greeting(APIHandler):
        @schema.validate(...)
        @gen.coroutine
        def get(self, fname, lname):
```

Then in this instance, the route will break:

    "/greeting/?", 
    "<class 'helloworld.Greeting'>"

**Comment by hfaran** [comment]
Oh, I see. I am assuming `coroutine` is swallowing the remainder of the argspec and changing the interface to the method so when `schema.validate` inspects it, it no longer sees them.
I will look into this further next week. Thanks for the update!

**Comment by malexh** [comment]
Hi. Have you had a chance to look into this issue?  Thanks :)

**Comment by hfaran** [comment]
Hi @malexh,

Apologies, I've been quite busy. I'm taking a look at it now, and will see if I can come up with any good solutions. Hopefully I will have a fix for your tonight.

**Comment by hfaran** [comment]
### Cause and Fix
As I expected earlier, it seems that losing the argspec caused route generation to break (as that is how Tornado-JSON is able to create routes based on method signatures). To fix this, I have implemented a replacement `gen.coroutine` which simply wraps Tornado's and annotates the signature as an attribute to the wrapper so it can be referenced later.

### Testing
Can you please:
* checkout the `hfaran_coroutine_fix` branch
* use `tornado_json.gen.coroutine` instead of `tornado.gen.coroutine`

and see if that fixes the issue for you? Based on simple testing with the *helloworld* demo, it **should** work. If it does, I will go ahead and merge it and create a new release tomorrow!

**Comment by malexh** [comment]
Great, thanks so much!  I spent a few hours testing today, and it is working nicely!  I have 19 routes now (each with a mix of GET/POST/PUT), and there weren't any collisions like before.  

I also did performance testing, and on average it seemed to be about 8% slower than the existing released version.  I'm guessing that could be due to the fact that I'm using sys.path.append to route to the Tornado-JSON folder rather than having it as an installed package. What do you think about that?

**Comment by hfaran** [comment]
It's great that it's working!

Hmm, are you using the exact same codebase (for your app) between v1.1.0 and this fix? Or is the performance difference after using `coroutine`s with the new fix and having the old one be synchronous?
I do not think using `sys.path.append` should matter, but you can install the checked out version with `python setup.py install` to make certain.

If you could give me any more details regarding the performance test, it would be greatly appreciated. :)

**Comment by malexh** [comment]
I wanted to give you another update here.  I've since set up some much more extensive load testing.  Overall, using tornado_json.gen.coroutine *did* improve the performance.  From my analysis, the main root causes that made me originally suspect this to be slower were:
1. too small of a data set (remedied with extensive performance tests using locust.io)
2. bottleneck in default nginx configs (remedied with performance tuning)
3. bottleneck in db performance (accounted for and will be remedied).

Viewing the results in small numbers (comparing 20 with and 20 without), it appeared that coroutines made it slower, especially because loads were so low.  With larger runs in the 10Ks, coroutines were on-par or, in most cases, faster.  In cases of heavy load, using coroutines was up to 36% faster for specific requests (eg. GET /X/Y), and 15% faster for a full user-behavior load (all requests combined with request weighting).

**Comment by hfaran** [comment]
This is very late; but thanks for the detailed numbers from May!
I will finally close this issue.
