### ISSUE TITLE
API_Documentation.md creating while Application creating is undocumented

### ISSUE THREAD

**Issue by rutsky** [hfaran/Tornado-JSON#62]
What are the reasons to use `tornado_json.Application` instead of `tornado.web.Application`?
I don't think that uncontrollable generation of documentation _on each run_ is good behavior.

**Comment by hfaran** [comment]
I completely agree with you, actually. The output generation should definitely be a command-line option; it just has not been done yet. I can look into making that change in a few days. It should be fairly trivial.

Of course, you're most definitely welcome to contribute a pull request with that change as well. :)

**Comment by dchaplinsky** [comment]
Any updates on this one? It still generates documentation on every run and this is very annoying (and not acceptable for production).

**Comment by hfaran** [comment]
A `generate_docs` parameter has been added to `tornado_json.web.Application`. By default, `API_Documentation` will **not** be generated anymore but it can be done so by setting `generate_docs` to `True`.
