### ISSUE TITLE
@validate already makes a coroutine; 1.2.0 release changes likely unnecessary

### ISSUE THREAD

**Issue by hfaran** [hfaran/Tornado-JSON#65]
- [ ] Should be added in documentation that if a method is decorated using `schema.validate` than it can be used asynchronously already.
- [ ] Addition of `tornado_json.gen.coroutine` should be reverted (as should all changes to docs etc. but tests should be kept for testing the breaks in #59)

**Comment by malexh** [comment]
Hi, I tried this on 1.2.0, but schema.validate did not allow the method to be used asynchronously. Once I added tornado_json.gen.coroutine to the method, it worked asynch.
