### ISSUE TITLE
API documentation for nonexistent routes generated when argspec and non-argspec method present in same handler

### ISSUE THREAD

**Issue by hfaran** [hfaran/Tornado-JSON#67]
Examples:
* https://github.com/hfaran/UBCRECSessions/blob/master/docs/API_Documentation.md#apisessionsessionpsession_ida-za-z0-9_
* https://github.com/hfaran/UBCRECSessions/blob/master/docs/API_Documentation.md#apisessionsession

Both of those have four methods listed when they shouldn't.

**Comment by mauler** [comment]
https://github.com/hfaran/Tornado-JSON/pull/90
