### ISSUE TITLE
optional parameters and logging

### ISSUE THREAD

**Issue by njordr** [hfaran/Tornado-JSON#82]
Hi hfaran.

How could I specify optional parameters in input_schema and how to catch the exception?

Thanks,
Giovanni

**Comment by hfaran** [comment]
Can you clarify what you mean by optional parameters with an example?

**Comment by njordr** [comment]
I have the following schema.validate:
input_schema={
            "type": "object",
            "properties": {
                "from": {"type": "string"},
                "to": {"type": "string"},
                "cc": {"type": "string"},
                "bcc": {"type": "string"},
                "subject": {"type": "string"},
                "body": {"type": "string"},
            }
        },
cc and bcc are optional, is there a way to achive this?
With this schema I have to insert all the fileds in the request

Thanks

**Comment by hfaran** [comment]
You can use the "required" field for this. For an example, see the examples that use "required" here: http://json-schema.org/example1.html

You can specify whatever JSONSchema compliant schema you like and it will work with Tornado-JSON. Hope this answers your question.
