### ISSUE TITLE
@schema.validate allow to transfer custom `IValidator` class that will be used to validate the instance.

### ISSUE THREAD

**Issue by rkaralkin** [hfaran/Tornado-JSON#85]
Hi,

I want use own jsonschema validator. 
Can you accept it in @schema.validate decorator
and than pass it to jsonschema.validate()

Same way as you doing with `format_checker`.

**Comment by hfaran** [comment]
Hey @rkaralkin I'm swamped at the moment so I don't know when I'll be able to get around to this. Feel free to submit a PR for this though and I can look at it!
