### ISSUE TITLE
Some problem in APIHander

### ISSUE THREAD

**Issue by Summersummer3** [hfaran/Tornado-JSON#93]
Even though I change the status to bad_request, the return json is still as followed:
`{
  "status": "success",
  "data": {
    "message": "bad request!"
  }
}`
and ajax dosen't response for status code 400

function return like this
`           self.set_status(httplib.BAD_REQUEST)
            return {
                "message": "bad request!"
            }
`

And I can't use `self.fail()` since the server will throw exception like this:
```
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado_json/jsend.py", line 20, in success
    self.write({'status': 'success', 'data': data})
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/web.py", line 690, in write
    raise RuntimeError("Cannot write() after finish()")
RuntimeError: Cannot write() after finish()

```

So what can I do?

**Comment by hfaran** [comment]
You need to use `api_assert` or `raise APIError` if you want to throw HTTP errors. This is discussed in the documentation [here](https://tornado-json.readthedocs.io/en/latest/requesthandler_guidelines.html#assertions), and if you want to see some examples, look [here](https://github.com/hfaran/CitySportsLeague-Server/blob/master/src/wlsports/api/game.py#L156) for an `api_assert` example, and [here](https://github.com/hfaran/CitySportsLeague-Server/blob/master/src/wlsports/api/game.py#L111) for an `APIError` example.

**Comment by hfaran** [comment]
You'll also notice that the documentation says not to use `self.fail` directly. ;)

**Comment by Summersummer3** [comment]
So sooooory I am not careful enough. Thanks for your response!
