### ISSUE TITLE
Incomplete response.py present in PyPI source distributions

### ISSUE THREAD

**Issue by djbright** [hfaran/Tornado-JSON#98]
Not sure what has happened here but the PyPI source distributions for v1.3.0 and v1.3.1 include an incomplete file `response.py` that is not tracked and not present in the github release archives.

We have a build step that involves mass 'compilation' of all *.py sources to *.pyc and that duly fails on this file

**Comment by hfaran** [comment]
I believe I was working on another branch and had an untracked response.py which was still there when I switched back to master to publish the 1.3.{0,1} releases.
I'll push out a 1.3.2 without the offending response.py some time today. Thanks for letting me know.

**Comment by hfaran** [comment]
[1.3.2](https://github.com/hfaran/Tornado-JSON/releases/tag/1.3.2) is now up on [PyPI](https://pypi.python.org/pypi/Tornado-JSON/1.3.2).

**Comment by hfaran** [comment]
Please verify if this fixes it for you.

**Comment by djbright** [comment]
@hfaran, yes all good, thanks again :) Your rapid response is also much appreciated!
